version: '3.3'
services:
  alist:
		container_name: alist
    image: 'xhofe/alist:latest'
    restart: unless-stopped
		network_mode: host
    volumes:
			- '/etc/localtime:/etc/localtime:ro'
      - '/etc/alist:/opt/alist/data'
    ports:
      - '5244:5244'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
