version: '3'
services:
  alist:
    image: xhofe/alist:latest
    container_name: alist
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - alist_data:/opt/alist/data
    ports:
      - '5244:5244'
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=022
volumes:
  alist_data: {}
