version: "3"

services:
  node-red:
    container_name: node-red
    image: nodered/node-red:latest
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data

volumes:
  node-red-data: {}

networks:
  node-red-net: {}