version: '3'
services:
  portainer_agent:
    container_name: portainer_agent
    image: "portainer/agent:latest"
    volumes:
			- /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
		ports:
			- '9001:9001'
   
