version: '3'
services:
  portainer:
    container_name: portainer-ce
    image: "portainer/portainer-ce:latest"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    ports:
      - '8000:8000'
      - '9000:9000'
volumes:
  portainer_data: {}